# METAR DATA

## Introduction
Metar stands for "Meteorological Terminal Air Report" and is therefore a documentation of meteorological data concerning specific airports.
Data was gathered from the Iowa ASOS network from the following link: __[https://mesonet.agron.iastate.edu/request/download.phtml](https://mesonet.agron.iastate.edu/request/download.phtml)__

For the codes within metar data we used __[https://www.theairlinepilots.com/forumarchive/aviation-weather/metar.pdf](https://www.theairlinepilots.com/forumarchive/aviation-weather/metar.pdf)__ to interpret their meanings

There have been found 193.033 entries with 31 columns.
## Dropped
For this project I dropped columns which are referring to the airport and are therefore equal in all rows.
- station (Abbreviation of airport - redundant)
- lon (longitude - airport longitude is known)
- lat (latitude - airport latitude is known)
- metar (unsure of use)

Additionally, valid was split up into time and date

## Missing and Trace values
Missing values are marked with M and trace values with T.
I replace missing and trace values (there were so few that this was deemed okay) values with pd.NaN to better use the functions provided by pandas/numpy

In [79]:
import pandas as pd
import re
import numpy as np
import os

from main.utils.data_manage_utils import read_table_from_subfolder

# Variables
ROOT_PATH = os.path.abspath("../../")
INPUT_FOLDER = os.path.join(ROOT_PATH, "data/input")
OUTPUT_FOLDER = os.path.join(ROOT_PATH, "data/preparation/prepped_files")

In [80]:
read_table_from_subfolder(os.path.join(INPUT_FOLDER,"data_raw/METAR_US/*_KATL_*.txt"))

C:\Users\chrig\PycharmProjects\PerturbationThesis\main\utils\data_manage_utils.py:170: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_table(filename, delimiter=delim)

,station,valid,lon,lat,tmpf,dwpf,relh,drct,sknt,p01i,...,skyl4,wxcodes,ice_accretion_1hr,ice_accretion_3hr,ice_accretion_6hr,peak_wind_gust,peak_wind_drct,peak_wind_time,feel,metar
0,ATL,2016-01-01 00:52,-84.4418,33.6301,51.98,42.08,68.86,320.00,10.00,0.00,...,25000.00,M,M,M,M,M,M,M,51.98,KATL 010052Z 32010KT 10SM FEW100 SCT150 BKN200...
1,ATL,2016-01-01 01:52,-84.4418,33.6301,50.00,41.00,71.07,330.00,7.00,0.00,...,M,M,M,M,M,M,M,M,46.72,KATL 010152Z 33007KT 10SM SCT150 BKN200 BKN250...
2,ATL,2016-01-01 02:52,-84.4418,33.6301,48.92,41.00,73.99,310.00,12.00,0.00,...,M,M,M,M,M,M,M,M,43.54,KATL 010252Z 31012KT 10SM FEW150 BKN200 BKN250...
3,ATL,2016-01-01 03:52,-84.4418,33.6301,46.94,39.92,76.43,320.00,13.00,0.00,...,M,M,M,M,M,M,M,M,40.71,KATL 010352Z 32013KT 10SM FEW150 SCT200 BKN250...
4,ATL,2016-01-01 04:52,-84.4418,33.6301,46.04,39.02,76.35,320.00,10.00,0.00,...,M,M,M,M,M,M,M,M,40.57,KATL 010452Z 32010KT 10SM FEW150 BKN200 BKN250...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193028,ATL,2017-12-30 23:40,-84.4418,33.6301,M,M,M,350.00,8.00,M,...,M,M,M,M,M,M,M,M,M,KATL 302340Z AUTO 35008KT 10SM 07/M01 A3008 RM...
193029,ATL,2017-12-30 23:45,-84.4418,33.6301,M,M,M,360.00,10.00,M,...,M,M,M,M,M,M,M,M,M,KATL 302345Z AUTO 36010KT 10SM 07/M01 A3008 RM...
193030,ATL,2017-12-30 23:50,-84.4418,33.6301,M,M,M,330.00,10.00,M,...,M,M,M,M,M,M,M,M,M,KATL 302350Z AUTO 33010KT 10SM 07/M01 A3009 RM...
193031,ATL,2017-12-30 23:52,-84.4418,33.6301,44.10,30.00,57.37,340.00,9.00,0.00,...,M,M,M,M,M,M,M,M,38.56,KATL 302352Z 34009KT 10SM FEW200 BKN250 07/M01...
193032,ATL,2017-12-30 23:55,-84.4418,33.6301,M,M,M,330.00,8.00,M,...,M,M,M,M,M,M,M,M,M,KATL 302355Z AUTO 33008KT 10SM 07/M01 A3009 RM...

In [81]:
atl_weather_df = read_table_from_subfolder(os.path.join(INPUT_FOLDER, "data_raw/METAR_US/*_KATL_*.txt"))
date = atl_weather_df["valid"].apply(lambda x: x.split()[0])
time = atl_weather_df["valid"].apply(lambda x: x.split()[1])
atl_weather_df = atl_weather_df.drop(labels=["station","lon", "lat","valid"], axis="columns")
atl_weather_df["date"] = date
atl_weather_df["time"] = time
atl_weather_df = atl_weather_df.mask(atl_weather_df == "M")
#atl_weather_df["valid"] = atl_weather_df["valid"].apply(lambda x: re.match('\d\d\d\d-\d\d-\d\d',x).group(0))
atl_weather_df

C:\Users\chrig\PycharmProjects\PerturbationThesis\main\utils\data_manage_utils.py:170: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_table(filename, delimiter=delim)

,tmpf,dwpf,relh,drct,sknt,p01i,alti,mslp,vsby,gust,...,ice_accretion_1hr,ice_accretion_3hr,ice_accretion_6hr,peak_wind_gust,peak_wind_drct,peak_wind_time,feel,metar,date,time
0,51.98,42.08,68.86,320.00,10.00,0.00,30.19,1022.50,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,51.98,KATL 010052Z 32010KT 10SM FEW100 SCT150 BKN200...,2016-01-01,00:52
1,50.00,41.00,71.07,330.00,7.00,0.00,30.18,1022.20,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,46.72,KATL 010152Z 33007KT 10SM SCT150 BKN200 BKN250...,2016-01-01,01:52
2,48.92,41.00,73.99,310.00,12.00,0.00,30.18,1022.00,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,43.54,KATL 010252Z 31012KT 10SM FEW150 BKN200 BKN250...,2016-01-01,02:52
3,46.94,39.92,76.43,320.00,13.00,0.00,30.17,1021.90,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,40.71,KATL 010352Z 32013KT 10SM FEW150 SCT200 BKN250...,2016-01-01,03:52
4,46.04,39.02,76.35,320.00,10.00,0.00,30.18,1022.00,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,40.57,KATL 010452Z 32010KT 10SM FEW150 BKN200 BKN250...,2016-01-01,04:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193028,NaN,NaN,NaN,350.00,8.00,NaN,30.08,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302340Z AUTO 35008KT 10SM 07/M01 A3008 RM...,2017-12-30,23:40
193029,NaN,NaN,NaN,360.00,10.00,NaN,30.08,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302345Z AUTO 36010KT 10SM 07/M01 A3008 RM...,2017-12-30,23:45
193030,NaN,NaN,NaN,330.00,10.00,NaN,30.09,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302350Z AUTO 33010KT 10SM 07/M01 A3009 RM...,2017-12-30,23:50
193031,44.10,30.00,57.37,340.00,9.00,0.00,30.09,1019.50,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,38.56,KATL 302352Z 34009KT 10SM FEW200 BKN250 07/M01...,2017-12-30,23:52
193032,NaN,NaN,NaN,330.00,8.00,NaN,30.09,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302355Z AUTO 33008KT 10SM 07/M01 A3009 RM...,2017-12-30,23:55

In [82]:
atl_weather_df["skyl4"].value_counts()

25000.00    971
20000.00    521
15000.00    213
13000.00     68
18000.00     41
14000.00     30
22000.00     18
30000.00      6
17000.00      3
19000.00      2
23000.00      1
24000.00      1
16000.00      1
25900.00      1
Name: skyl4, dtype: int64

In [83]:
from main.utils import data_manage_utils
import importlib
importlib.reload(data_manage_utils)
atl_weather_df_analyse = atl_weather_df.copy(deep=True)

cardinal_columns=["tmpf", "dwpf", "relh", "drct", "sknt", "p01i", "alti", "mslp", "vsby", "gust", "skyl1", "skyl2", "skyl3", "skyl4", "ice_accretion_1hr", "ice_accretion_3hr", "ice_accretion_6hr", "peak_wind_gust", "peak_wind_drct", "feel"]
atl_weather_df_analyse = data_manage_utils.convert_specified_columns(atl_weather_df_analyse, columns_to_convert=cardinal_columns, placeholders=["T"])
atl_weather_df_analyse

,tmpf,dwpf,relh,drct,sknt,p01i,alti,mslp,vsby,gust,...,ice_accretion_1hr,ice_accretion_3hr,ice_accretion_6hr,peak_wind_gust,peak_wind_drct,peak_wind_time,feel,metar,date,time
0,51.98,42.08,68.86,320,10,0.0,30.19,1022.5,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,51.98,KATL 010052Z 32010KT 10SM FEW100 SCT150 BKN200...,2016-01-01,00:52
1,50.00,41.00,71.07,330,7,0.0,30.18,1022.2,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,46.72,KATL 010152Z 33007KT 10SM SCT150 BKN200 BKN250...,2016-01-01,01:52
2,48.92,41.00,73.99,310,12,0.0,30.18,1022.0,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,43.54,KATL 010252Z 31012KT 10SM FEW150 BKN200 BKN250...,2016-01-01,02:52
3,46.94,39.92,76.43,320,13,0.0,30.17,1021.9,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,40.71,KATL 010352Z 32013KT 10SM FEW150 SCT200 BKN250...,2016-01-01,03:52
4,46.04,39.02,76.35,320,10,0.0,30.18,1022.0,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,40.57,KATL 010452Z 32010KT 10SM FEW150 BKN200 BKN250...,2016-01-01,04:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193028,NaN,NaN,NaN,350,8,NaN,30.08,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 302340Z AUTO 35008KT 10SM 07/M01 A3008 RM...,2017-12-30,23:40
193029,NaN,NaN,NaN,360,10,NaN,30.08,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 302345Z AUTO 36010KT 10SM 07/M01 A3008 RM...,2017-12-30,23:45
193030,NaN,NaN,NaN,330,10,NaN,30.09,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 302350Z AUTO 33010KT 10SM 07/M01 A3009 RM...,2017-12-30,23:50
193031,44.10,30.00,57.37,340,9,0.0,30.09,1019.5,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,38.56,KATL 302352Z 34009KT 10SM FEW200 BKN250 07/M01...,2017-12-30,23:52
193032,NaN,NaN,NaN,330,8,NaN,30.09,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 302355Z AUTO 33008KT 10SM 07/M01 A3009 RM...,2017-12-30,23:55

In [84]:
atl_weather_df

,tmpf,dwpf,relh,drct,sknt,p01i,alti,mslp,vsby,gust,...,ice_accretion_1hr,ice_accretion_3hr,ice_accretion_6hr,peak_wind_gust,peak_wind_drct,peak_wind_time,feel,metar,date,time
0,51.98,42.08,68.86,320.00,10.00,0.00,30.19,1022.50,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,51.98,KATL 010052Z 32010KT 10SM FEW100 SCT150 BKN200...,2016-01-01,00:52
1,50.00,41.00,71.07,330.00,7.00,0.00,30.18,1022.20,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,46.72,KATL 010152Z 33007KT 10SM SCT150 BKN200 BKN250...,2016-01-01,01:52
2,48.92,41.00,73.99,310.00,12.00,0.00,30.18,1022.00,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,43.54,KATL 010252Z 31012KT 10SM FEW150 BKN200 BKN250...,2016-01-01,02:52
3,46.94,39.92,76.43,320.00,13.00,0.00,30.17,1021.90,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,40.71,KATL 010352Z 32013KT 10SM FEW150 SCT200 BKN250...,2016-01-01,03:52
4,46.04,39.02,76.35,320.00,10.00,0.00,30.18,1022.00,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,40.57,KATL 010452Z 32010KT 10SM FEW150 BKN200 BKN250...,2016-01-01,04:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193028,NaN,NaN,NaN,350.00,8.00,NaN,30.08,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302340Z AUTO 35008KT 10SM 07/M01 A3008 RM...,2017-12-30,23:40
193029,NaN,NaN,NaN,360.00,10.00,NaN,30.08,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302345Z AUTO 36010KT 10SM 07/M01 A3008 RM...,2017-12-30,23:45
193030,NaN,NaN,NaN,330.00,10.00,NaN,30.09,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302350Z AUTO 33010KT 10SM 07/M01 A3009 RM...,2017-12-30,23:50
193031,44.10,30.00,57.37,340.00,9.00,0.00,30.09,1019.50,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,38.56,KATL 302352Z 34009KT 10SM FEW200 BKN250 07/M01...,2017-12-30,23:52
193032,NaN,NaN,NaN,330.00,8.00,NaN,30.09,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302355Z AUTO 33008KT 10SM 07/M01 A3009 RM...,2017-12-30,23:55

In [85]:
atl_weather_df_analyse.isna().sum()

tmpf                 172637
dwpf                 172639
relh                 172669
drct                   5400
sknt                   4879
p01i                 168570
alti                     31
mslp                 175544
vsby                      0
gust                 187790
skyc1                  7644
skyc2                146844
skyc3                172045
skyc4                191156
skyl1                 96692
skyl2                146844
skyl3                172045
skyl4                191156
wxcodes              175124
ice_accretion_1hr    193022
ice_accretion_3hr    193031
ice_accretion_6hr    193031
peak_wind_gust       192464
peak_wind_drct       192464
peak_wind_time       192464
feel                 172669
metar                  1702
date                      0
time                      0
dtype: int64

In [86]:
atl_weather_df.isna().sum()

tmpf                 172637
dwpf                 172639
relh                 172669
drct                   5400
sknt                   4879
p01i                 166716
alti                     31
mslp                 175544
vsby                      0
gust                 187790
skyc1                  7644
skyc2                146844
skyc3                172045
skyc4                191156
skyl1                 96692
skyl2                146844
skyl3                172045
skyl4                191156
wxcodes              175124
ice_accretion_1hr    193011
ice_accretion_3hr    193029
ice_accretion_6hr    193029
peak_wind_gust       192464
peak_wind_drct       192464
peak_wind_time       192464
feel                 172669
metar                  1702
date                      0
time                      0
dtype: int64

In [87]:
atl_weather_df[atl_weather_df["alti"].isna()]

,tmpf,dwpf,relh,drct,sknt,p01i,alti,mslp,vsby,gust,...,ice_accretion_1hr,ice_accretion_3hr,ice_accretion_6hr,peak_wind_gust,peak_wind_drct,peak_wind_time,feel,metar,date,time
4707,NaN,NaN,NaN,250.00,6.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 050055Z AUTO 25006KT 10SM BKN070 OVC085 R...,2016-05-05,00:55
25893,NaN,NaN,NaN,220.00,8.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 112155Z AUTO 22008KT 10SM CLR RMK LTG DS...,2016-07-11,21:55
82268,NaN,NaN,NaN,330.00,9.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 081450Z AUTO 33009KT 10SM CLR RMK MADISHF,2017-01-08,14:50
82270,NaN,NaN,NaN,330.00,9.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 081455Z AUTO 33009KT 10SM CLR RMK MADISHF,2017-01-08,14:55
82271,NaN,NaN,NaN,340.00,11.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 081500Z AUTO 34011KT 10SM CLR RMK MADISHF,2017-01-08,15:00
82272,NaN,NaN,NaN,330.00,12.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 081505Z AUTO 33012KT 10SM CLR RMK MADISHF,2017-01-08,15:05
82273,NaN,NaN,NaN,320.00,11.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 081510Z AUTO 32011KT 10SM CLR RMK MADISHF,2017-01-08,15:10
82274,NaN,NaN,NaN,320.00,10.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 081515Z AUTO 32010KT 10SM CLR RMK MADISHF,2017-01-08,15:15
82275,NaN,NaN,NaN,330.00,11.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 081520Z AUTO 33011KT 10SM CLR RMK MADISHF,2017-01-08,15:20
82276,NaN,NaN,NaN,330.00,11.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 081525Z AUTO 33011KT 10SM CLR RMK MADISHF,2017-01-08,15:25
82277,NaN,NaN,NaN,330.00,10.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 081530Z AUTO 33010KT 10SM CLR RMK MADISHF,2017-01-08,15:30
82278,NaN,NaN,NaN,330.00,8.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 081535Z AUTO 33008KT 10SM CLR RMK MADISHF,2017-01-08,15:35
82279,NaN,NaN,NaN,330.00,9.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 081540Z AUTO 33009KT 10SM CLR RMK MADISHF,2017-01-08,15:40
82280,NaN,NaN,NaN,330.00,9.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 081545Z AUTO 33009KT 10SM CLR RMK MADISHF,2017-01-08,15:45
82281,NaN,NaN,NaN,350.00,9.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 081550Z AUTO 35009KT 10SM CLR RMK MADISHF,2017-01-08,15:50
82283,NaN,NaN,NaN,350.00,10.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 081555Z AUTO 35010KT 10SM CLR RMK MADISHF,2017-01-08,15:55
82284,NaN,NaN,NaN,330.00,9.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 081600Z AUTO 33009KT 10SM CLR RMK MADISHF,2017-01-08,16:00
82285,NaN,NaN,NaN,330.00,12.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 081605Z AUTO 33012KT 10SM CLR RMK WND 30V...,2017-01-08,16:05
108775,NaN,NaN,NaN,180.00,10.00,0.01,NaN,NaN,4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 031855Z AUTO 18010KT 4SM -RA BR SCT070 OV...,2017-04-03,18:55
158403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 111555Z AUTO /////KT 8SM -RA OVC015 RMK M...,2017-09-11,15:55
185967,NaN,NaN,NaN,350.00,8.00,NaN,NaN,NaN,5.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 081755Z AUTO 35008KT 5SM -RA BR BKN004 OV...,2017-12-08,17:55
186913,NaN,NaN,NaN,290.00,3.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 111655Z AUTO 29003KT 10SM CLR RMK VRB03KT...,2017-12-11,16:55
186914,NaN,NaN,NaN,260.00,6.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 111700Z AUTO 26006KT 10SM CLR 11/01 RMK T...,2017-12-11,17:00
186916,NaN,NaN,NaN,220.00,3.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 111710Z AUTO 22003KT 10SM CLR 11/00 RMK T...,2017-12-11,17:10
188798,NaN,NaN,NaN,110.00,4.00,NaN,NaN,NaN,6.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 171755Z AUTO 11004KT 6SM -RA BKN090 OVC10...,2017-12-17,17:55
191692,NaN,NaN,NaN,160.00,9.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 261655Z AUTO 16009KT 10SM CLR 07/M08 RMK ...,2017-12-26,16:55
191705,NaN,NaN,NaN,120.00,5.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 261755Z AUTO 12005KT 10SM CLR 08/M09 RMK ...,2017-12-26,17:55
191887,NaN,NaN,NaN,60.00,6.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 270755Z AUTO 06006KT 10SM OVC079 04/M01 R...,2017-12-27,07:55
192316,NaN,NaN,NaN,100.00,10.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 281655Z AUTO 10010KT 10SM CLR 06/M03 RMK ...,2017-12-28,16:55
192342,NaN,NaN,NaN,70.00,6.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 281855Z AUTO 07006KT 10SM FEW043 07/M03 R...,2017-12-28,18:55
192641,NaN,NaN,NaN,310.00,6.00,NaN,NaN,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 291755Z AUTO 31006KT 10SM CLR 09/M02 RMK ...,2017-12-29,17:55

In [88]:
atl_weather_df_analyse[atl_weather_df_analyse["alti"].isna()]

,tmpf,dwpf,relh,drct,sknt,p01i,alti,mslp,vsby,gust,...,ice_accretion_1hr,ice_accretion_3hr,ice_accretion_6hr,peak_wind_gust,peak_wind_drct,peak_wind_time,feel,metar,date,time
4707,NaN,NaN,NaN,250,6,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 050055Z AUTO 25006KT 10SM BKN070 OVC085 R...,2016-05-05,00:55
25893,NaN,NaN,NaN,220,8,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 112155Z AUTO 22008KT 10SM CLR RMK LTG DS...,2016-07-11,21:55
82268,NaN,NaN,NaN,330,9,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 081450Z AUTO 33009KT 10SM CLR RMK MADISHF,2017-01-08,14:50
82270,NaN,NaN,NaN,330,9,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 081455Z AUTO 33009KT 10SM CLR RMK MADISHF,2017-01-08,14:55
82271,NaN,NaN,NaN,340,11,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 081500Z AUTO 34011KT 10SM CLR RMK MADISHF,2017-01-08,15:00
82272,NaN,NaN,NaN,330,12,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 081505Z AUTO 33012KT 10SM CLR RMK MADISHF,2017-01-08,15:05
82273,NaN,NaN,NaN,320,11,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 081510Z AUTO 32011KT 10SM CLR RMK MADISHF,2017-01-08,15:10
82274,NaN,NaN,NaN,320,10,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 081515Z AUTO 32010KT 10SM CLR RMK MADISHF,2017-01-08,15:15
82275,NaN,NaN,NaN,330,11,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 081520Z AUTO 33011KT 10SM CLR RMK MADISHF,2017-01-08,15:20
82276,NaN,NaN,NaN,330,11,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 081525Z AUTO 33011KT 10SM CLR RMK MADISHF,2017-01-08,15:25
82277,NaN,NaN,NaN,330,10,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 081530Z AUTO 33010KT 10SM CLR RMK MADISHF,2017-01-08,15:30
82278,NaN,NaN,NaN,330,8,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 081535Z AUTO 33008KT 10SM CLR RMK MADISHF,2017-01-08,15:35
82279,NaN,NaN,NaN,330,9,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 081540Z AUTO 33009KT 10SM CLR RMK MADISHF,2017-01-08,15:40
82280,NaN,NaN,NaN,330,9,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 081545Z AUTO 33009KT 10SM CLR RMK MADISHF,2017-01-08,15:45
82281,NaN,NaN,NaN,350,9,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 081550Z AUTO 35009KT 10SM CLR RMK MADISHF,2017-01-08,15:50
82283,NaN,NaN,NaN,350,10,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 081555Z AUTO 35010KT 10SM CLR RMK MADISHF,2017-01-08,15:55
82284,NaN,NaN,NaN,330,9,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 081600Z AUTO 33009KT 10SM CLR RMK MADISHF,2017-01-08,16:00
82285,NaN,NaN,NaN,330,12,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 081605Z AUTO 33012KT 10SM CLR RMK WND 30V...,2017-01-08,16:05
108775,NaN,NaN,NaN,180,10,0.01,NaN,NaN,4.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 031855Z AUTO 18010KT 4SM -RA BR SCT070 OV...,2017-04-03,18:55
158403,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,NaN,8.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 111555Z AUTO /////KT 8SM -RA OVC015 RMK M...,2017-09-11,15:55
185967,NaN,NaN,NaN,350,8,NaN,NaN,NaN,5.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 081755Z AUTO 35008KT 5SM -RA BR BKN004 OV...,2017-12-08,17:55
186913,NaN,NaN,NaN,290,3,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 111655Z AUTO 29003KT 10SM CLR RMK VRB03KT...,2017-12-11,16:55
186914,NaN,NaN,NaN,260,6,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 111700Z AUTO 26006KT 10SM CLR 11/01 RMK T...,2017-12-11,17:00
186916,NaN,NaN,NaN,220,3,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 111710Z AUTO 22003KT 10SM CLR 11/00 RMK T...,2017-12-11,17:10
188798,NaN,NaN,NaN,110,4,NaN,NaN,NaN,6.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 171755Z AUTO 11004KT 6SM -RA BKN090 OVC10...,2017-12-17,17:55
191692,NaN,NaN,NaN,160,9,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 261655Z AUTO 16009KT 10SM CLR 07/M08 RMK ...,2017-12-26,16:55
191705,NaN,NaN,NaN,120,5,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 261755Z AUTO 12005KT 10SM CLR 08/M09 RMK ...,2017-12-26,17:55
191887,NaN,NaN,NaN,60,6,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 270755Z AUTO 06006KT 10SM OVC079 04/M01 R...,2017-12-27,07:55
192316,NaN,NaN,NaN,100,10,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 281655Z AUTO 10010KT 10SM CLR 06/M03 RMK ...,2017-12-28,16:55
192342,NaN,NaN,NaN,70,6,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 281855Z AUTO 07006KT 10SM FEW043 07/M03 R...,2017-12-28,18:55
192641,NaN,NaN,NaN,310,6,NaN,NaN,NaN,10.0,<NA>,...,NaN,NaN,NaN,<NA>,<NA>,NaN,NaN,KATL 291755Z AUTO 31006KT 10SM CLR 09/M02 RMK ...,2017-12-29,17:55

In [89]:
# Find rows with no null values
complete_rows_mask = atl_weather_df_analyse.notna().all(axis=1)
# Get the complete rows and their indices
complete_rows = atl_weather_df_analyse[complete_rows_mask]
complete_rows

Empty DataFrame
Columns: [tmpf, dwpf, relh, drct, sknt, p01i, alti, mslp, vsby, gust, skyc1, skyc2, skyc3, skyc4, skyl1, skyl2, skyl3, skyl4, wxcodes, ice_accretion_1hr, ice_accretion_3hr, ice_accretion_6hr, peak_wind_gust, peak_wind_drct, peak_wind_time, feel, metar, date, time]
Index: []

[0 rows x 29 columns]

In [90]:
atl_weather_df_analyse[atl_weather_df_analyse["ice_accretion_1hr"] == "T"]

Empty DataFrame
Columns: [tmpf, dwpf, relh, drct, sknt, p01i, alti, mslp, vsby, gust, skyc1, skyc2, skyc3, skyc4, skyl1, skyl2, skyl3, skyl4, wxcodes, ice_accretion_1hr, ice_accretion_3hr, ice_accretion_6hr, peak_wind_gust, peak_wind_drct, peak_wind_time, feel, metar, date, time]
Index: []

[0 rows x 29 columns]

In [91]:
atl_weather_df_analyse["ice_accretion_1hr"].iloc[637]

nan

In [92]:
from main.utils import data_manage_utils
print(data_manage_utils.describe_dataframe_structure(atl_weather_df_analyse).to_latex(escape=False, index=False))

\begin{tabular}{lllrl}
\toprule
             Name &   Type &          Range &  # Null &                                            Example \\
\midrule
             tmpf &  float &   [15.1;98.96] &  172637 &                                              51.98 \\
             dwpf &  float &     [1.0;77.0] &  172639 &                                              42.08 \\
             relh &  float &   [8.99;100.0] &  172669 &                                              68.86 \\
             drct &    int &        [0;360] &    5400 &                                                320 \\
             sknt &    int &         [0;39] &    4879 &                                                 10 \\
             p01i &  float &     [0.0;1.84] &  168570 &                                                0.0 \\
             alti &  float &   [29.15;30.7] &      31 &                                              30.19 \\
             mslp &  float & [987.1;1041.2] &  175544 &                                             1022.5 \\
             vsby &  float &    [0.12;10.0] &       0 &                                               10.0 \\
             gust &    int &        [13;53] &  187790 &                                                 16 \\
            skyc1 & string &      char(3-3) &    7644 &                                                FEW \\
            skyc2 & string &      char(3-3) &  146844 &                                                SCT \\
            skyc3 & string &      char(3-3) &  172045 &                                                BKN \\
            skyc4 & string &      char(3-3) &  191156 &                                                BKN \\
            skyl1 &    int &      [0;30000] &   96692 &                                              10000 \\
            skyl2 &    int &    [400;30000] &  146844 &                                              15000 \\
            skyl3 &    int &    [800;30000] &  172045 &                                              20000 \\
            skyl4 &    int &  [13000;30000] &  191156 &                                              25000 \\
          wxcodes & string &     char(2-14) &  175124 &                                                -RA \\
ice_accretion_1hr &  float &    [0.01;0.07] &  193022 &                                               0.03 \\
ice_accretion_3hr &  float &    [0.07;0.13] &  193031 &                                               0.13 \\
ice_accretion_6hr &  float &    [0.07;0.24] &  193031 &                                               0.24 \\
   peak_wind_gust &    int &        [26;56] &  192464 &                                                 26 \\
   peak_wind_drct &    int &       [10;360] &  192464 &                                                320 \\
   peak_wind_time & string &     char(3-16) &  192464 &                                   2016-01-04 19:10 \\
             feel &  float &  [1.11;104.55] &  172669 &                                              51.98 \\
            metar & string &    char(3-225) &    1702 & KATL 010052Z 32010KT 10SM FEW100 SCT150 BKN200 ... \\
             date & string &    char(10-10) &       0 &                                         2016-01-01 \\
             time & string &      char(5-5) &       0 &                                              00:52 \\
\bottomrule
\end{tabular}

C:\Users\chrig\AppData\Local\Temp\ipykernel_9776\3655621452.py:2: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(data_manage_utils.describe_dataframe_structure(atl_weather_df_analyse).to_latex(escape=False, index=False))

In [4]:
from main.utils import data_manage_utils
import importlib
importlib.reload(data_manage_utils)
print(data_manage_utils.col_stats_to_table(atl_weather_df, headers=["name","type","range","null","example"]).style.to_latex())

\begin{tabular}{llllll}
 & Name & Type & Range & # Null & Example \\
0 & tmpf & object & char(5.0-5.0) & 172637 & 51.98 \\
1 & dwpf & object & char(4.0-5.0) & 172639 & 42.08 \\
2 & relh & object & char(4.0-6.0) & 172669 & 68.86 \\
3 & drct & object & char(4.0-6.0) & 5400 & 320.00 \\
4 & sknt & object & char(4.0-5.0) & 4879 & 10.00 \\
5 & p01i & object & char(1.0-4.0) & 166716 & 0.00 \\
6 & alti & object & char(5.0-5.0) & 31 & 30.19 \\
7 & mslp & object & char(6.0-7.0) & 175544 & 1022.50 \\
8 & vsby & float64 & [0.12;10.0] & 0 & 10.000000 \\
9 & gust & object & char(5.0-5.0) & 187790 & nan \\
10 & skyc1 & object & char(3.0-3.0) & 7644 & FEW \\
11 & skyc2 & object & char(3.0-3.0) & 146844 & SCT \\
12 & skyc3 & object & char(3.0-3.0) & 172045 & BKN \\
13 & skyc4 & object & char(3.0-3.0) & 191156 & BKN \\
14 & skyl1 & object & char(4.0-8.0) & 96692 & 10000.00 \\
15 & skyl2 & object & char(6.0-8.0) & 146844 & 15000.00 \\
16 & skyl3 & object & char(6.0-8.0) & 172045 & 20000.00 \\
17 & skyl4 & object & char(8.0-8.0) & 191156 & 25000.00 \\
18 & wxcodes & object & char(2.0-14.0) & 175124 & nan \\
19 & ice_accretion_1hr & object & char(1.0-4.0) & 193011 & nan \\
20 & ice_accretion_3hr & object & char(1.0-4.0) & 193029 & nan \\
21 & ice_accretion_6hr & object & char(1.0-4.0) & 193029 & nan \\
22 & peak_wind_gust & object & char(5.0-5.0) & 192464 & nan \\
23 & peak_wind_drct & object & char(5.0-6.0) & 192464 & nan \\
24 & peak_wind_time & object & char(16.0-16.0) & 192464 & nan \\
25 & feel & object & char(4.0-6.0) & 172669 & 51.98 \\
26 & metar & object & char(41.0-225.0) & 1702 & KATL 010052Z 32010KT 10SM FEW100 SCT150 BKN200 BKN250 11/06 A3019 RMK AO2 SLP225 T01110056 \\
27 & date & object & char(10-10) & 0 & 2016-01-01 \\
28 & time & object & char(5-5) & 0 & 00:52 \\
\end{tabular}

In [5]:
atl_weather_df["wxcodes"].unique()

array([nan, '-RA', 'RA BR', '-DZ BR', '-RA BR', 'BR', '+RA', '+RA BR',
       'HZ', '-PLSN BR', '-SN BR', '-SNRA BR', '-SN', 'FG', 'BR BCFG',
       'RA', '+TSRA BR', '+TSRA', '-TSRA BR', 'TS', '+TSRA SQ', 'TSRA',
       'TSRA BR', '-RAPL', 'PLRA', 'RAPL', '-TSRA', '-DZ', 'DZ BR', 'FU',
       '-RA SQ', 'TSRA SQ', '-TSRA SQ', '+RA SQ', 'VCTS', 'VCTS -RA',
       'VCTS +RA BR', 'VCTS -RA BR', '+TSRA FG', '+RA FG', '-DZ FG',
       '-RA FG', 'UP', '-FZRA', '-FZRA BR', 'FZRA BR', '-FZRAPL',
       '-FZRA -PL', '-FZRAPL BR', '-SNPL BR', 'UP BR', 'BCFG', 'SQ',
       'TS SQ', 'HZ FU', '-TSDZ', 'VCTS RA BR', 'BCFG BR', 'MIFG BR',
       'MIFG', '-PLRA BR', '-RA -PL BR', 'RA -PL BR', '-PLRA', '-RA -PL',
       '-PLSN', '-SNPLRA', '-PL -SN BR', '-PLSNRA BR', '-RA -PL -SN BR',
       '-RAPL BR', '-RA -SN BR', '-RASNPL BR', '-SNRAGS BR',
       '-RA -SN -BR', '-RASNGS BR', '-RA -SN', '-RASN BR', '-RASN',
       '-DZ BR BCFG', '-DZ BCFG BR'], dtype=object)

In [6]:
atl_weather_df["gust"].unique()

array([nan, '16.00', '18.00', '19.00', '20.00', '22.00', '23.00', '21.00',
       '25.00', '17.00', '24.00', '27.00', '15.00', '28.00', '29.00',
       '30.00', '26.00', '32.00', '33.00', '31.00', '34.00', '14.00',
       '35.00', '48.00', '49.00', '42.00', '40.00', '36.00', '39.00',
       '43.00', '38.00', '13.00', '44.00', '53.00', '46.00', '41.00',
       '45.00', '51.00', '37.00'], dtype=object)

In [7]:
print("Counting 'T' values per column")
for col in atl_weather_df.columns:
    val_cnt = atl_weather_df[col].value_counts()
    if 'T' in val_cnt.index:
        print(col + ":\t"+ str(val_cnt.loc["T"]))
    else:
        print(col + ":\t0")

Counting 'T' values per column
tmpf:	0
dwpf:	0
relh:	0
drct:	0
sknt:	0
p01i:	1854
alti:	0
mslp:	0
vsby:	0
gust:	0
skyc1:	0
skyc2:	0
skyc3:	0
skyc4:	0
skyl1:	0
skyl2:	0
skyl3:	0
skyl4:	0
wxcodes:	0
ice_accretion_1hr:	11
ice_accretion_3hr:	2
ice_accretion_6hr:	2
peak_wind_gust:	0
peak_wind_drct:	0
peak_wind_time:	0
feel:	0
metar:	0
date:	0
time:	0

In [8]:
atl_weather_df = atl_weather_df.mask(atl_weather_df == "T")
atl_weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193033 entries, 0 to 193032
Data columns (total 29 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   tmpf               20396 non-null   object
 1   dwpf               20394 non-null   object
 2   relh               20364 non-null   object
 3   drct               187633 non-null  object
 4   sknt               188154 non-null  object
 5   p01i               24463 non-null   object
 6   alti               193002 non-null  object
 7   mslp               17489 non-null   object
 8   vsby               193033 non-null  float64
 9   gust               5243 non-null    object
 10  skyc1              185389 non-null  object
 11  skyc2              46189 non-null   object
 12  skyc3              20988 non-null   object
 13  skyc4              1877 non-null    object
 14  skyl1              96341 non-null   object
 15  skyl2              46189 non-null   object
 16  skyl3              20988 non-null   object
 17  skyl4              1877 non-null    object
 18  wxcodes            17909 non-null   object
 19  ice_accretion_1hr  11 non-null      object
 20  ice_accretion_3hr  2 non-null       object
 21  ice_accretion_6hr  2 non-null       object
 22  peak_wind_gust     569 non-null     object
 23  peak_wind_drct     569 non-null     object
 24  peak_wind_time     569 non-null     object
 25  feel               20364 non-null   object
 26  metar              191331 non-null  object
 27  date               193033 non-null  object
 28  time               193033 non-null  object
dtypes: float64(1), object(28)
memory usage: 42.7+ MB

In [9]:
#atl_weather_df = num_df.join(str_df)
atl_weather_df

,tmpf,dwpf,relh,drct,sknt,p01i,alti,mslp,vsby,gust,...,ice_accretion_1hr,ice_accretion_3hr,ice_accretion_6hr,peak_wind_gust,peak_wind_drct,peak_wind_time,feel,metar,date,time
0,51.98,42.08,68.86,320.00,10.00,0.00,30.19,1022.50,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,51.98,KATL 010052Z 32010KT 10SM FEW100 SCT150 BKN200...,2016-01-01,00:52
1,50.00,41.00,71.07,330.00,7.00,0.00,30.18,1022.20,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,46.72,KATL 010152Z 33007KT 10SM SCT150 BKN200 BKN250...,2016-01-01,01:52
2,48.92,41.00,73.99,310.00,12.00,0.00,30.18,1022.00,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,43.54,KATL 010252Z 31012KT 10SM FEW150 BKN200 BKN250...,2016-01-01,02:52
3,46.94,39.92,76.43,320.00,13.00,0.00,30.17,1021.90,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,40.71,KATL 010352Z 32013KT 10SM FEW150 SCT200 BKN250...,2016-01-01,03:52
4,46.04,39.02,76.35,320.00,10.00,0.00,30.18,1022.00,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,40.57,KATL 010452Z 32010KT 10SM FEW150 BKN200 BKN250...,2016-01-01,04:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193028,NaN,NaN,NaN,350.00,8.00,NaN,30.08,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302340Z AUTO 35008KT 10SM 07/M01 A3008 RM...,2017-12-30,23:40
193029,NaN,NaN,NaN,360.00,10.00,NaN,30.08,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302345Z AUTO 36010KT 10SM 07/M01 A3008 RM...,2017-12-30,23:45
193030,NaN,NaN,NaN,330.00,10.00,NaN,30.09,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302350Z AUTO 33010KT 10SM 07/M01 A3009 RM...,2017-12-30,23:50
193031,44.10,30.00,57.37,340.00,9.00,0.00,30.09,1019.50,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,38.56,KATL 302352Z 34009KT 10SM FEW200 BKN250 07/M01...,2017-12-30,23:52
193032,NaN,NaN,NaN,330.00,8.00,NaN,30.09,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302355Z AUTO 33008KT 10SM 07/M01 A3009 RM...,2017-12-30,23:55

In [10]:
def print_inv_nan_perc(df):
    print("Counting non-null percentage per column")
    for col in df.columns:
        perc = round(1 - (df[col].isna().sum() / df.__len__()),2)
        print(col + ":\t" + str(perc))
print_inv_nan_perc(atl_weather_df)

Counting non-null percentage per column
tmpf:	0.11
dwpf:	0.11
relh:	0.11
drct:	0.97
sknt:	0.97
p01i:	0.13
alti:	1.0
mslp:	0.09
vsby:	1.0
gust:	0.03
skyc1:	0.96
skyc2:	0.24
skyc3:	0.11
skyc4:	0.01
skyl1:	0.5
skyl2:	0.24
skyl3:	0.11
skyl4:	0.01
wxcodes:	0.09
ice_accretion_1hr:	0.0
ice_accretion_3hr:	0.0
ice_accretion_6hr:	0.0
peak_wind_gust:	0.0
peak_wind_drct:	0.0
peak_wind_time:	0.0
feel:	0.11
metar:	0.99
date:	1.0
time:	1.0

In [11]:
#Dropping all columns with missing metar data
atl_weather_df = atl_weather_df.drop(atl_weather_df[atl_weather_df["metar"].isnull()].index)
atl_weather_df

,tmpf,dwpf,relh,drct,sknt,p01i,alti,mslp,vsby,gust,...,ice_accretion_1hr,ice_accretion_3hr,ice_accretion_6hr,peak_wind_gust,peak_wind_drct,peak_wind_time,feel,metar,date,time
0,51.98,42.08,68.86,320.00,10.00,0.00,30.19,1022.50,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,51.98,KATL 010052Z 32010KT 10SM FEW100 SCT150 BKN200...,2016-01-01,00:52
1,50.00,41.00,71.07,330.00,7.00,0.00,30.18,1022.20,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,46.72,KATL 010152Z 33007KT 10SM SCT150 BKN200 BKN250...,2016-01-01,01:52
2,48.92,41.00,73.99,310.00,12.00,0.00,30.18,1022.00,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,43.54,KATL 010252Z 31012KT 10SM FEW150 BKN200 BKN250...,2016-01-01,02:52
3,46.94,39.92,76.43,320.00,13.00,0.00,30.17,1021.90,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,40.71,KATL 010352Z 32013KT 10SM FEW150 SCT200 BKN250...,2016-01-01,03:52
4,46.04,39.02,76.35,320.00,10.00,0.00,30.18,1022.00,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,40.57,KATL 010452Z 32010KT 10SM FEW150 BKN200 BKN250...,2016-01-01,04:52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193028,NaN,NaN,NaN,350.00,8.00,NaN,30.08,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302340Z AUTO 35008KT 10SM 07/M01 A3008 RM...,2017-12-30,23:40
193029,NaN,NaN,NaN,360.00,10.00,NaN,30.08,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302345Z AUTO 36010KT 10SM 07/M01 A3008 RM...,2017-12-30,23:45
193030,NaN,NaN,NaN,330.00,10.00,NaN,30.09,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302350Z AUTO 33010KT 10SM 07/M01 A3009 RM...,2017-12-30,23:50
193031,44.10,30.00,57.37,340.00,9.00,0.00,30.09,1019.50,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,38.56,KATL 302352Z 34009KT 10SM FEW200 BKN250 07/M01...,2017-12-30,23:52
193032,NaN,NaN,NaN,330.00,8.00,NaN,30.09,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302355Z AUTO 33008KT 10SM 07/M01 A3009 RM...,2017-12-30,23:55

In [12]:
metar_dict = {
    'TS' : 'Thunderstorm',
    'RA' : 'Rain',
    'DZ' : 'Drizzle',
    'SN' : 'Snow',
    'SG' : 'Snow Grains',
    'IC' : 'Ice Pellets',
    'GR' : 'Hail',
    'GS' : 'Small Hail',
    'FG' : 'FG',
    'VA' : 'Volcanic Ashe',
    'BR' : 'Mist',
    'HZ' : 'Haze',
    'DU' : 'Dust',
    'FU' : 'Smoke',
    'SA' : 'Sand',
    'PY' : 'Spray'
}

In [13]:
def find_event(metar: str):
    ret = []
    for event in [ele for ele in list(metar_dict.keys()) if(ele in metar)]:
        pos = str.find(metar, event)
        if metar[pos - 1] == "-" or metar[pos - 1] == "+":
            ret.append(metar[pos-1] + event)
        else:
            ret.append(event)
    if len(ret) > 0:
        return ret
    else:
        return np.nan

atl_weather_df["events"] = atl_weather_df["metar"].apply(lambda x: find_event(x))
print("Length of events: " + str(len(atl_weather_df[~atl_weather_df["events"].isna()])) + ". From " +str(len(atl_weather_df)) + " total entries.")
atl_weather_df["events"][~atl_weather_df["events"].isna()].value_counts()

Length of events: 27140. From 191331 total entries.

[SN]                     6209
[-RA]                    4123
[BR]                     3683
[-RA, BR]                2154
[-DZ, BR]                1296
                         ...
[-TS, RA, BR]               1
[+TS, RA, SN, IC, FG]       1
[RA, FU]                    1
[SN, FG]                    1
[DZ, FG, BR]                1
Name: events, Length: 122, dtype: int64

In [14]:
atl_weather_df

,tmpf,dwpf,relh,drct,sknt,p01i,alti,mslp,vsby,gust,...,ice_accretion_3hr,ice_accretion_6hr,peak_wind_gust,peak_wind_drct,peak_wind_time,feel,metar,date,time,events
0,51.98,42.08,68.86,320.00,10.00,0.00,30.19,1022.50,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,51.98,KATL 010052Z 32010KT 10SM FEW100 SCT150 BKN200...,2016-01-01,00:52,NaN
1,50.00,41.00,71.07,330.00,7.00,0.00,30.18,1022.20,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,46.72,KATL 010152Z 33007KT 10SM SCT150 BKN200 BKN250...,2016-01-01,01:52,NaN
2,48.92,41.00,73.99,310.00,12.00,0.00,30.18,1022.00,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,43.54,KATL 010252Z 31012KT 10SM FEW150 BKN200 BKN250...,2016-01-01,02:52,NaN
3,46.94,39.92,76.43,320.00,13.00,0.00,30.17,1021.90,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,40.71,KATL 010352Z 32013KT 10SM FEW150 SCT200 BKN250...,2016-01-01,03:52,NaN
4,46.04,39.02,76.35,320.00,10.00,0.00,30.18,1022.00,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,40.57,KATL 010452Z 32010KT 10SM FEW150 BKN200 BKN250...,2016-01-01,04:52,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193028,NaN,NaN,NaN,350.00,8.00,NaN,30.08,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302340Z AUTO 35008KT 10SM 07/M01 A3008 RM...,2017-12-30,23:40,NaN
193029,NaN,NaN,NaN,360.00,10.00,NaN,30.08,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302345Z AUTO 36010KT 10SM 07/M01 A3008 RM...,2017-12-30,23:45,NaN
193030,NaN,NaN,NaN,330.00,10.00,NaN,30.09,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302350Z AUTO 33010KT 10SM 07/M01 A3009 RM...,2017-12-30,23:50,NaN
193031,44.10,30.00,57.37,340.00,9.00,0.00,30.09,1019.50,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,38.56,KATL 302352Z 34009KT 10SM FEW200 BKN250 07/M01...,2017-12-30,23:52,NaN
193032,NaN,NaN,NaN,330.00,8.00,NaN,30.09,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302355Z AUTO 33008KT 10SM 07/M01 A3009 RM...,2017-12-30,23:55,NaN

In [15]:
print_inv_nan_perc(atl_weather_df)

Counting non-null percentage per column
tmpf:	0.11
dwpf:	0.11
relh:	0.11
drct:	0.97
sknt:	0.97
p01i:	0.13
alti:	1.0
mslp:	0.09
vsby:	1.0
gust:	0.03
skyc1:	0.96
skyc2:	0.24
skyc3:	0.11
skyc4:	0.01
skyl1:	0.5
skyl2:	0.24
skyl3:	0.11
skyl4:	0.01
wxcodes:	0.09
ice_accretion_1hr:	0.0
ice_accretion_3hr:	0.0
ice_accretion_6hr:	0.0
peak_wind_gust:	0.0
peak_wind_drct:	0.0
peak_wind_time:	0.0
feel:	0.11
metar:	1.0
date:	1.0
time:	1.0
events:	0.14

In [16]:
atl_weather_df = atl_weather_df.sort_values(by=["date","time"]).reset_index(drop=True)
atl_weather_df

,tmpf,dwpf,relh,drct,sknt,p01i,alti,mslp,vsby,gust,...,ice_accretion_3hr,ice_accretion_6hr,peak_wind_gust,peak_wind_drct,peak_wind_time,feel,metar,date,time,events
0,51.98,42.08,68.86,320.00,10.00,0.00,30.19,1022.50,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,51.98,KATL 010052Z 32010KT 10SM FEW100 SCT150 BKN200...,2016-01-01,00:52,NaN
1,50.00,41.00,71.07,330.00,7.00,0.00,30.18,1022.20,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,46.72,KATL 010152Z 33007KT 10SM SCT150 BKN200 BKN250...,2016-01-01,01:52,NaN
2,48.92,41.00,73.99,310.00,12.00,0.00,30.18,1022.00,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,43.54,KATL 010252Z 31012KT 10SM FEW150 BKN200 BKN250...,2016-01-01,02:52,NaN
3,46.94,39.92,76.43,320.00,13.00,0.00,30.17,1021.90,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,40.71,KATL 010352Z 32013KT 10SM FEW150 SCT200 BKN250...,2016-01-01,03:52,NaN
4,46.04,39.02,76.35,320.00,10.00,0.00,30.18,1022.00,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,40.57,KATL 010452Z 32010KT 10SM FEW150 BKN200 BKN250...,2016-01-01,04:52,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191326,NaN,NaN,NaN,350.00,8.00,NaN,30.08,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302340Z AUTO 35008KT 10SM 07/M01 A3008 RM...,2017-12-30,23:40,NaN
191327,NaN,NaN,NaN,360.00,10.00,NaN,30.08,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302345Z AUTO 36010KT 10SM 07/M01 A3008 RM...,2017-12-30,23:45,NaN
191328,NaN,NaN,NaN,330.00,10.00,NaN,30.09,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302350Z AUTO 33010KT 10SM 07/M01 A3009 RM...,2017-12-30,23:50,NaN
191329,44.10,30.00,57.37,340.00,9.00,0.00,30.09,1019.50,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,38.56,KATL 302352Z 34009KT 10SM FEW200 BKN250 07/M01...,2017-12-30,23:52,NaN
191330,NaN,NaN,NaN,330.00,8.00,NaN,30.09,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,KATL 302355Z AUTO 33008KT 10SM 07/M01 A3009 RM...,2017-12-30,23:55,NaN

In [17]:
atl_weather_df["time"] = atl_weather_df["time"].apply(lambda x: x.split(":")[0])
atl_weather_df = atl_weather_df.drop(["metar"], axis="columns")
atl_weather_df

,tmpf,dwpf,relh,drct,sknt,p01i,alti,mslp,vsby,gust,...,ice_accretion_1hr,ice_accretion_3hr,ice_accretion_6hr,peak_wind_gust,peak_wind_drct,peak_wind_time,feel,date,time,events
0,51.98,42.08,68.86,320.00,10.00,0.00,30.19,1022.50,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,51.98,2016-01-01,00,NaN
1,50.00,41.00,71.07,330.00,7.00,0.00,30.18,1022.20,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,46.72,2016-01-01,01,NaN
2,48.92,41.00,73.99,310.00,12.00,0.00,30.18,1022.00,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,43.54,2016-01-01,02,NaN
3,46.94,39.92,76.43,320.00,13.00,0.00,30.17,1021.90,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,40.71,2016-01-01,03,NaN
4,46.04,39.02,76.35,320.00,10.00,0.00,30.18,1022.00,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,40.57,2016-01-01,04,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191326,NaN,NaN,NaN,350.00,8.00,NaN,30.08,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-30,23,NaN
191327,NaN,NaN,NaN,360.00,10.00,NaN,30.08,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-30,23,NaN
191328,NaN,NaN,NaN,330.00,10.00,NaN,30.09,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-30,23,NaN
191329,44.10,30.00,57.37,340.00,9.00,0.00,30.09,1019.50,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,38.56,2017-12-30,23,NaN
191330,NaN,NaN,NaN,330.00,8.00,NaN,30.09,NaN,10.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-30,23,NaN

In [18]:
def list_to_string(lst):
    ret = ""
    if type(lst) == list:
        for cnt,x in enumerate(lst):
            ret = ret + str(x)
            if cnt != len(lst) - 1:
                ret = ret + " "
        return ret
    else:
        return lst
atl_weather_df["events"] = atl_weather_df["events"].apply(lambda x: list_to_string(x))

In [19]:
one_hot = pd.get_dummies(atl_weather_df["events"].str.split(expand=True)).groupby(lambda x: x.split('_')[-1], axis = 1).sum()

In [20]:
idx = atl_weather_df[~pd.isna(atl_weather_df["events"])]["events"].index
atl_weather_df[~pd.isna(atl_weather_df["events"])]["events"]

181       -RA
182       -RA
183       -RA
184       -RA
185       -RA
         ...
191206     FU
191207     FU
191208     FU
191209     FU
191210     FU
Name: events, Length: 27140, dtype: object

In [21]:
one_hot.loc[idx]

,+RA,+TS,-BR,-DZ,-RA,-SG,-SN,-TS,BR,DZ,FG,FU,GR,GS,HZ,IC,RA,SN,TS
181,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
182,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
183,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
184,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
185,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191206,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
191207,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
191208,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
191209,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
191210,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0

In [22]:
for col in one_hot.columns:
    if col[0] == "+":
        one_hot[col] = one_hot[col].apply(lambda x: x*3)
    elif col[0] == "-":
        pass
    else:
        one_hot[col] = one_hot[col].apply(lambda x: x*2)
one_hot.loc[idx]

,+RA,+TS,-BR,-DZ,-RA,-SG,-SN,-TS,BR,DZ,FG,FU,GR,GS,HZ,IC,RA,SN,TS
181,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
182,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
183,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
184,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
185,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191206,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0
191207,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0
191208,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0
191209,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0
191210,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0

In [23]:
one_hot = one_hot.groupby(lambda x: re.sub("[^a-zA-Z]+","",x), axis=1).sum()
one_hot = one_hot.add_prefix('EVENT_')
one_hot.loc[idx]

,EVENT_BR,EVENT_DZ,EVENT_FG,EVENT_FU,EVENT_GR,EVENT_GS,EVENT_HZ,EVENT_IC,EVENT_RA,EVENT_SG,EVENT_SN,EVENT_TS
181,0,0,0,0,0,0,0,0,1,0,0,0
182,0,0,0,0,0,0,0,0,1,0,0,0
183,0,0,0,0,0,0,0,0,1,0,0,0
184,0,0,0,0,0,0,0,0,1,0,0,0
185,0,0,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
191206,0,0,0,2,0,0,0,0,0,0,0,0
191207,0,0,0,2,0,0,0,0,0,0,0,0
191208,0,0,0,2,0,0,0,0,0,0,0,0
191209,0,0,0,2,0,0,0,0,0,0,0,0
191210,0,0,0,2,0,0,0,0,0,0,0,0

In [68]:
atl_weather_df = atl_weather_df.join(one_hot)
atl_weather_df

,tmpf,dwpf,relh,drct,sknt,p01i,alti,mslp,vsby,gust,...,EVENT_FG,EVENT_FU,EVENT_GR,EVENT_GS,EVENT_HZ,EVENT_IC,EVENT_RA,EVENT_SG,EVENT_SN,EVENT_TS
0,51.98,42.08,68.86,320.00,10.00,0.00,30.19,1022.50,10.0,NaN,...,0,0,0,0,0,0,0,0,0,0
1,50.00,41.00,71.07,330.00,7.00,0.00,30.18,1022.20,10.0,NaN,...,0,0,0,0,0,0,0,0,0,0
2,48.92,41.00,73.99,310.00,12.00,0.00,30.18,1022.00,10.0,NaN,...,0,0,0,0,0,0,0,0,0,0
3,46.94,39.92,76.43,320.00,13.00,0.00,30.17,1021.90,10.0,NaN,...,0,0,0,0,0,0,0,0,0,0
4,46.04,39.02,76.35,320.00,10.00,0.00,30.18,1022.00,10.0,NaN,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191326,NaN,NaN,NaN,350.00,8.00,NaN,30.08,NaN,10.0,NaN,...,0,0,0,0,0,0,0,0,0,0
191327,NaN,NaN,NaN,360.00,10.00,NaN,30.08,NaN,10.0,NaN,...,0,0,0,0,0,0,0,0,0,0
191328,NaN,NaN,NaN,330.00,10.00,NaN,30.09,NaN,10.0,NaN,...,0,0,0,0,0,0,0,0,0,0
191329,44.10,30.00,57.37,340.00,9.00,0.00,30.09,1019.50,10.0,NaN,...,0,0,0,0,0,0,0,0,0,0
191330,NaN,NaN,NaN,330.00,8.00,NaN,30.09,NaN,10.0,NaN,...,0,0,0,0,0,0,0,0,0,0

In [69]:
atl_weather_df = atl_weather_df.drop(["events"], axis="columns")

In [70]:
str_cols=["skyc1","skyc2","skyc3","skyc4","wxcodes","peak_wind_time","time","date"]
num_cols =  []
for col in atl_weather_df.columns:
    if col not in str_cols and col not in list(one_hot.columns) :
        num_cols.append(col)
        atl_weather_df[col] = atl_weather_df[col].astype('float64')
atl_weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 191331 entries, 0 to 191330
Data columns (total 40 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   tmpf               20396 non-null   float64
 1   dwpf               20394 non-null   float64
 2   relh               20364 non-null   float64
 3   drct               185963 non-null  float64
 4   sknt               186484 non-null  float64
 5   p01i               24455 non-null   float64
 6   alti               191300 non-null  float64
 7   mslp               17489 non-null   float64
 8   vsby               191331 non-null  float64
 9   gust               5231 non-null    float64
 10  skyc1              183723 non-null  object
 11  skyc2              45906 non-null   object
 12  skyc3              20899 non-null   object
 13  skyc4              1877 non-null    object
 14  skyl1              95651 non-null   float64
 15  skyl2              45906 non-null   float64
 16  skyl3              20899 non-null   float64
 17  skyl4              1877 non-null    float64
 18  wxcodes            17890 non-null   object
 19  ice_accretion_1hr  11 non-null      float64
 20  ice_accretion_3hr  2 non-null       float64
 21  ice_accretion_6hr  2 non-null       float64
 22  peak_wind_gust     569 non-null     float64
 23  peak_wind_drct     569 non-null     float64
 24  peak_wind_time     569 non-null     object
 25  feel               20364 non-null   float64
 26  date               191331 non-null  object
 27  time               191331 non-null  object
 28  EVENT_BR           191331 non-null  int64
 29  EVENT_DZ           191331 non-null  int64
 30  EVENT_FG           191331 non-null  int64
 31  EVENT_FU           191331 non-null  int64
 32  EVENT_GR           191331 non-null  int64
 33  EVENT_GS           191331 non-null  int64
 34  EVENT_HZ           191331 non-null  int64
 35  EVENT_IC           191331 non-null  int64
 36  EVENT_RA           191331 non-null  int64
 37  EVENT_SG           191331 non-null  int64
 38  EVENT_SN           191331 non-null  int64
 39  EVENT_TS           191331 non-null  int64
dtypes: float64(20), int64(12), object(8)
memory usage: 58.4+ MB

In [71]:
str_df = atl_weather_df[str_cols].groupby(["date","time"]).agg(lambda x: np.nan if len(pd.Series.mode(x)) == 0 else pd.Series.mode(x)[0])
str_df

                skyc1 skyc2 skyc3 skyc4 wxcodes peak_wind_time
date       time
2016-01-01 00     FEW   SCT   BKN   BKN     NaN            NaN
           01     SCT   BKN   BKN   NaN     NaN            NaN
           02     FEW   BKN   BKN   NaN     NaN            NaN
           03     FEW   SCT   BKN   NaN     NaN            NaN
           04     FEW   BKN   BKN   NaN     NaN            NaN
...               ...   ...   ...   ...     ...            ...
2017-12-30 19     FEW   FEW   NaN   NaN     NaN            NaN
           20     FEW   NaN   NaN   NaN     NaN            NaN
           21     BKN   NaN   NaN   NaN     NaN            NaN
           22     CLR   BKN   NaN   NaN     NaN            NaN
           23     FEW   BKN   NaN   NaN     NaN            NaN

[17520 rows x 6 columns]

In [83]:
atl_weather_df[atl_weather_df["date"] == "2016-04-30"]

,tmpf,dwpf,relh,drct,sknt,p01i,alti,mslp,vsby,gust,...,EVENT_FG,EVENT_FU,EVENT_GR,EVENT_GS,EVENT_HZ,EVENT_IC,EVENT_RA,EVENT_SG,EVENT_SN,EVENT_TS
3353,78.98,51.08,37.78,0.0,0.0,0.00,29.97,1013.9,10.0,NaN,...,0,0,0,0,0,0,0,0,0,0
3354,78.98,51.08,37.78,330.0,4.0,0.00,29.99,1014.4,10.0,NaN,...,0,0,0,0,0,0,0,0,0,0
3355,73.04,55.94,55.01,320.0,6.0,0.00,30.01,1015.2,10.0,NaN,...,0,0,0,0,0,0,0,0,0,0
3356,71.96,55.94,57.05,320.0,5.0,0.00,30.01,1015.1,10.0,NaN,...,0,0,0,0,0,0,0,0,0,0
3357,73.04,53.96,51.18,0.0,0.0,0.00,29.99,1014.3,10.0,NaN,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3459,NaN,NaN,NaN,210.0,11.0,0.08,29.96,NaN,4.0,NaN,...,0,0,0,0,0,2,3,0,2,2
3460,NaN,NaN,NaN,200.0,13.0,0.15,29.96,NaN,3.0,NaN,...,0,0,0,0,0,2,3,0,2,2
3461,NaN,NaN,NaN,NaN,NaN,0.18,29.97,NaN,3.0,NaN,...,0,0,0,0,0,2,3,0,2,2
3462,69.08,64.94,86.66,200.0,15.0,0.22,29.97,1014.2,3.0,25.0,...,0,0,0,0,0,2,2,0,0,3
3463,NaN,NaN,NaN,NaN,NaN,0.06,29.98,NaN,3.0,NaN,...,0,0,0,0,0,2,3,0,2,2

In [84]:
atl_weather_df[atl_weather_df["date"] == "2016-05-01"]

,tmpf,dwpf,relh,drct,sknt,p01i,alti,mslp,vsby,gust,...,EVENT_FG,EVENT_FU,EVENT_GR,EVENT_GS,EVENT_HZ,EVENT_IC,EVENT_RA,EVENT_SG,EVENT_SN,EVENT_TS
3464,NaN,NaN,NaN,140.0,8.0,0.09,29.98,NaN,6.0,NaN,...,0,0,0,0,0,2,1,0,2,2
3465,NaN,NaN,NaN,140.0,7.0,0.10,29.97,NaN,6.0,NaN,...,0,0,0,0,0,2,1,0,2,2
3466,NaN,NaN,NaN,110.0,8.0,0.10,29.96,NaN,6.0,NaN,...,0,0,0,0,0,2,1,0,2,2
3467,NaN,NaN,NaN,100.0,7.0,0.11,29.95,NaN,6.0,NaN,...,0,0,0,0,0,2,1,0,2,2
3468,NaN,NaN,NaN,160.0,3.0,0.11,29.95,NaN,9.0,NaN,...,0,0,0,0,0,2,1,0,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3784,NaN,NaN,NaN,230.0,3.0,NaN,30.03,NaN,10.0,NaN,...,0,0,0,0,0,0,0,0,2,0
3785,NaN,NaN,NaN,0.0,0.0,NaN,30.03,NaN,9.0,NaN,...,0,0,0,0,0,0,0,0,2,0
3786,73.04,68.00,84.22,280.0,3.0,0.00,30.03,1016.1,9.0,NaN,...,0,0,0,0,0,0,0,0,0,0
3787,NaN,NaN,NaN,290.0,3.0,NaN,30.02,NaN,10.0,NaN,...,0,0,0,0,0,2,0,0,2,2
3788,73.04,69.08,87.41,290.0,3.0,0.00,30.02,NaN,10.0,NaN,...,0,0,0,0,0,2,0,0,0,2

In [41]:
num_df = atl_weather_df[num_cols + ["date","time"]].groupby(["date","time"]).median()
num_df

                  tmpf   dwpf   relh   drct  sknt  p01i   alti    mslp  vsby  \
date       time
2016-01-01 00    51.98  42.08  68.86  320.0  10.0   0.0  30.19  1022.5  10.0
           01    50.00  41.00  71.07  330.0   7.0   0.0  30.18  1022.2  10.0
           02    48.92  41.00  73.99  310.0  12.0   0.0  30.18  1022.0  10.0
           03    46.94  39.92  76.43  320.0  13.0   0.0  30.17  1021.9  10.0
           04    46.04  39.02  76.35  320.0  10.0   0.0  30.18  1022.0  10.0
...                ...    ...    ...    ...   ...   ...    ...     ...   ...
2017-12-30 19    50.00  32.00  49.81  290.0  12.0   0.0  30.07  1018.6  10.0
           20    51.10  32.00  47.81  300.0  11.0   0.0  30.06  1018.6  10.0
           21    48.00  30.90  51.34  300.0  11.0   0.0  30.07  1018.9  10.0
           22    46.00  30.90  55.36  290.0   9.0   0.0  30.07  1018.9  10.0
           23    44.10  30.00  57.37  320.0   7.0   0.0  30.08  1019.5  10.0

                 gust    skyl1    skyl2    skyl3    skyl4  ice_accretion_1hr  \
date       time
2016-01-01 00     NaN  10000.0  15000.0  20000.0  25000.0                NaN
           01     NaN  15000.0  20000.0  25000.0      NaN                NaN
           02     NaN  15000.0  20000.0  25000.0      NaN                NaN
           03     NaN  15000.0  20000.0  25000.0      NaN                NaN
           04     NaN  15000.0  20000.0  25000.0      NaN                NaN
...               ...      ...      ...      ...      ...                ...
2017-12-30 19    20.5   3999.0  25000.0      NaN      NaN                NaN
           20     NaN   3999.0      NaN      NaN      NaN                NaN
           21    16.0  25000.0      NaN      NaN      NaN                NaN
           22     NaN  20000.0  25000.0      NaN      NaN                NaN
           23     NaN  20000.0  25000.0      NaN      NaN                NaN

                 ice_accretion_3hr  ice_accretion_6hr  peak_wind_gust  \
date       time
2016-01-01 00                  NaN                NaN             NaN
           01                  NaN                NaN             NaN
           02                  NaN                NaN             NaN
           03                  NaN                NaN             NaN
           04                  NaN                NaN             NaN
...                            ...                ...             ...
2017-12-30 19                  NaN                NaN             NaN
           20                  NaN                NaN             NaN
           21                  NaN                NaN             NaN
           22                  NaN                NaN             NaN
           23                  NaN                NaN             NaN

                 peak_wind_drct   feel
date       time
2016-01-01 00               NaN  51.98
           01               NaN  46.72
           02               NaN  43.54
           03               NaN  40.71
           04               NaN  40.57
...                         ...    ...
2017-12-30 19               NaN  44.63
           20               NaN  51.10
           21               NaN  43.03
           22               NaN  40.92
           23               NaN  38.56

[17520 rows x 20 columns]

In [42]:
oh_df = atl_weather_df[["date","time"] + list(one_hot.columns)].groupby(["date","time"]).max()
oh_df

                 EVENT_BR  EVENT_DZ  EVENT_FG  EVENT_FU  EVENT_GR  EVENT_GS  \
date       time
2016-01-01 00           0         0         0         0         0         0
           01           0         0         0         0         0         0
           02           0         0         0         0         0         0
           03           0         0         0         0         0         0
           04           0         0         0         0         0         0
...                   ...       ...       ...       ...       ...       ...
2017-12-30 19           0         0         0         0         0         0
           20           0         0         0         0         0         0
           21           0         0         0         0         0         0
           22           0         0         0         0         0         0
           23           0         0         0         0         0         0

                 EVENT_HZ  EVENT_IC  EVENT_RA  EVENT_SG  EVENT_SN  EVENT_TS
date       time
2016-01-01 00           0         0         0         0         0         0
           01           0         0         0         0         0         0
           02           0         0         0         0         0         0
           03           0         0         0         0         0         0
           04           0         0         0         0         0         0
...                   ...       ...       ...       ...       ...       ...
2017-12-30 19           0         0         0         0         0         0
           20           0         0         0         0         0         0
           21           0         0         0         0         0         0
           22           0         0         0         0         0         0
           23           0         0         0         0         0         0

[17520 rows x 12 columns]

In [43]:
atl_weather_df = num_df.join(str_df)
atl_weather_df = atl_weather_df.join(oh_df)
print_inv_nan_perc(atl_weather_df)
atl_weather_df = atl_weather_df.drop(["peak_wind_time","peak_wind_gust","peak_wind_drct","peak_wind_time","ice_accretion_1hr", "ice_accretion_3hr","ice_accretion_6hr", "skyl1", "skyl2", "skyl3", "skyl4", "skyc1", "skyc2", "skyc3", "skyc4", "gust"], axis="columns")
atl_weather_df

Counting non-null percentage per column
tmpf:	1.0
dwpf:	1.0
relh:	1.0
drct:	1.0
sknt:	1.0
p01i:	0.95
alti:	1.0
mslp:	1.0
vsby:	1.0
gust:	0.16
skyl1:	0.87
skyl2:	0.61
skyl3:	0.36
skyl4:	0.09
ice_accretion_1hr:	0.0
ice_accretion_3hr:	0.0
ice_accretion_6hr:	0.0
peak_wind_gust:	0.03
peak_wind_drct:	0.03
feel:	1.0
skyc1:	1.0
skyc2:	0.61
skyc3:	0.36
skyc4:	0.09
wxcodes:	0.13
peak_wind_time:	0.03
EVENT_BR:	1.0
EVENT_DZ:	1.0
EVENT_FG:	1.0
EVENT_FU:	1.0
EVENT_GR:	1.0
EVENT_GS:	1.0
EVENT_HZ:	1.0
EVENT_IC:	1.0
EVENT_RA:	1.0
EVENT_SG:	1.0
EVENT_SN:	1.0
EVENT_TS:	1.0

                  tmpf   dwpf   relh   drct  sknt  p01i   alti    mslp  vsby  \
date       time
2016-01-01 00    51.98  42.08  68.86  320.0  10.0   0.0  30.19  1022.5  10.0
           01    50.00  41.00  71.07  330.0   7.0   0.0  30.18  1022.2  10.0
           02    48.92  41.00  73.99  310.0  12.0   0.0  30.18  1022.0  10.0
           03    46.94  39.92  76.43  320.0  13.0   0.0  30.17  1021.9  10.0
           04    46.04  39.02  76.35  320.0  10.0   0.0  30.18  1022.0  10.0
...                ...    ...    ...    ...   ...   ...    ...     ...   ...
2017-12-30 19    50.00  32.00  49.81  290.0  12.0   0.0  30.07  1018.6  10.0
           20    51.10  32.00  47.81  300.0  11.0   0.0  30.06  1018.6  10.0
           21    48.00  30.90  51.34  300.0  11.0   0.0  30.07  1018.9  10.0
           22    46.00  30.90  55.36  290.0   9.0   0.0  30.07  1018.9  10.0
           23    44.10  30.00  57.37  320.0   7.0   0.0  30.08  1019.5  10.0

                  feel  ... EVENT_FG  EVENT_FU  EVENT_GR  EVENT_GS  EVENT_HZ  \
date       time         ...
2016-01-01 00    51.98  ...        0         0         0         0         0
           01    46.72  ...        0         0         0         0         0
           02    43.54  ...        0         0         0         0         0
           03    40.71  ...        0         0         0         0         0
           04    40.57  ...        0         0         0         0         0
...                ...  ...      ...       ...       ...       ...       ...
2017-12-30 19    44.63  ...        0         0         0         0         0
           20    51.10  ...        0         0         0         0         0
           21    43.03  ...        0         0         0         0         0
           22    40.92  ...        0         0         0         0         0
           23    38.56  ...        0         0         0         0         0

                 EVENT_IC  EVENT_RA  EVENT_SG  EVENT_SN  EVENT_TS
date       time
2016-01-01 00           0         0         0         0         0
           01           0         0         0         0         0
           02           0         0         0         0         0
           03           0         0         0         0         0
           04           0         0         0         0         0
...                   ...       ...       ...       ...       ...
2017-12-30 19           0         0         0         0         0
           20           0         0         0         0         0
           21           0         0         0         0         0
           22           0         0         0         0         0
           23           0         0         0         0         0

[17520 rows x 23 columns]

In [44]:
atl_weather_df.to_pickle(os.path.join(OUTPUT_FOLDER, "05_metar.pkl"))